driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private box in Chef's Atlas account
      provider: vmware_fusion
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
  - name: default
    run_list:
      - recipe[build-essential]
      - recipe[homebrew::default]
      - recipe[homebrew::cask]
      - recipe[homebrew::install_formulas]
      - recipe[homebrew::install_casks]
      - recipe[homebrew::install_taps]
    attributes:
      homebrew:
        formulas:
          - redis
        casks:
          - caffeine
        taps:
          - homebrew/homebrew-games
